Update package.json
Fixed dependencies. "Request" now have a fixed version.  

This error is now fixed:
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.